<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-S5T2SER" failures="1" tests="6" name="allTestsInAPackage" time="1.166" errors="0" timestamp="27 3æœˆ 2019 06:50:53 GMT">
  <testcase classname="framework.runner.TestNG" name="testRequest" time="0.938"/>
  <testcase classname="framework.runner.TestNG" name="testRequest" time="0.049"/>
  <testcase classname="framework.runner.TestNG" name="testRequest" time="0.043"/>
  <testcase classname="framework.runner.TestNG" name="testRequest" time="0.04">
    <skipped/>
  </testcase> <!-- testRequest -->
  <testcase classname="framework.runner.TestNG" name="testRequest" time="0.036">
    <skipped/>
  </testcase> <!-- testRequest -->
  <testcase classname="framework.runner.TestNG" name="testRequest" time="0.039">
    <failure type="java.lang.AssertionError" message=" expected [success] but found [error]">
      <![CDATA[java.lang.AssertionError:  expected [success] but found [error]
at yamlModel.Comparator$1.comparator(Comparator.java:14)
at framework.runner.TestNG.checkResponse(TestNG.java:82)
at framework.runner.TestNG.testRequest(TestNG.java:124)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testRequest -->
</testsuite> <!-- allTestsInAPackage -->
